apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: project-earthflower
  name: project-earthflower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-earthflower
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: project-earthflower
    spec:
      containers:
        - image: httpd:2.4.41-alpine
          name: httpd
          volumeMounts: test-vol
            - mountPaths: '/Volumes/Data'
      volumes:
        - name: test-vol
          emptyDir: {}