apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
  labels:
    app: kubia
spec:
  replicas: 3
  selector:
    app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
        - name: kubia
          image: luksa/kubia:1.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443

---

apiVersion: v1
kind: Service
metadata:
  name: kubia
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
  selector:
    app: kubia
